modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="milkeysdecoration"
version="2.0.0-alpha.1+201001"
displayName="Milkey's Decoration"
credits="Created by Milkeyyy using MCreator - https://mcreator.net/about"
displayURL="http://bit.ly/midews"
authors="Milkeyyy"
description='''
Version changelog: http://bit.ly/midecl-v2
'''

[[dependencies.milkeysdecoration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




