modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="milkeysdecorate"
version="1.2.1-release+200401"
displayName="Milkey's Decoration"
credits="Created by Milkeyyy using MCreator - https://mcreator.net/about"
displayURL="http://bit.ly/midews"
authors="Milkeyyy"
description='''
Version changelog: https://bit.ly/midecl Current version: http://bit.ly/midecv Tools used: MCreator, MrCrayfish's Model Creator, paint.net
'''

[[dependencies.milkeysdecorate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



